#!/bin/sh # -*- mode: shell-script -*-
release=$(date '+%F')

# Make directories
mkdir yamwi
mkdir yamwi/help
mkdir yamwi/packages

# Copy files
cp index.php yamwi
cp style.css yamwi
cp README.org yamwi
cp INSTALL yamwi
cp LICENSE yamwi
cp yamwi.* yamwi
cp yamwi-conf.php yamwi
cp help/*.html yamwi/help
cp help/help.css yamwi/help
cp packages/*.mac yamwi/packages
cp packages/*.lisp yamwi/packages
cp favicon.ico yamwi

# Packaging
tar -czvf yamwi-${release}.tar.gz yamwi

# Remove folder
rm -r yamwi
