#+TITLE: Introduction to Yamwi
#+OPTIONS: ^:{} toc:nil num:nil
#+AUTHOR: Leo Butler (based on README_en by Mario Rodríguez Riotorto)
#+MACRO: yamwiurl https://github.com/leo-butler/yamwi/
#+EMAIL: leo.butler@university.ca (university = UManitoba)

* Objectives
*Yamwi* ([[https://github.com/leo-butler/yamwi/][Yet Another Maxima Web Interface]]) is a web interface, based
on Linux+Apache+Php, to the computer algebra system *Maxima*
([[https://maxima.sourceforge.io/]]).

Maxima is the free version (GPL) of the Macsyma system developed in
Lisp at MIT beginning in the late nineteen sixties; other similar
programs (Mathematica, Maple) got inspired by it in the
eighties. Since 2000 Maxima is part of Sourceforge and maintained by
an international team of programers. Due to its advanced routines,
Maxima is also used in research and technical contexts.

Yamwi is of interest in educational contexts, to make interactive
activities with the browser, or to show mathematical concepts. All
sorts of computations and graphics can be made through the web by
Yamwi.

The original author of this software is Mario Rodríguez Riotorto. The
current maintainer is Leo Butler. See [[*Contact][contact information]].

* Requirements
The operating system to install Yamwi is Linux.

Software requirements on the server side:

- Apache :: (https://www.apache.org/). (Ver. >= 2).
- Php :: (https://www.php.net/). (Ver. >= 5).
- Gnuplot :: (http://www.gnuplot.info/). This is the program used by Maxima for rendering graphics. (Ver. >= 4.2).
- Maxima :: (https://maxima.sourceforge.io/). This is the mathematical engine. (Ver. >= 5.20).
- timelimit/timeout :: (https://devel.ringlet.net/sysutils/timelimit/ / https://www.gnu.org/software/coreutils/). Bound Maxima's computation time to a fixed limit.

In case the administrator wants to render results in binary TeX
format, the following packages must be also installed (see
configuration variable =$mode= below):

- dvips (from LaTeX)
- texi2dvi (from texinfo)
- convert (from ImageMagick)

* Installation
Once the above-mentioned programs are installed, Yamwi's installation
is as easy as placing the Yamwi's files somewhere accesible to Apache.

Yamwi's source can be downloaded from {{{yamwiurl}}}.

This is the installation process: (requires root privileges)

1. Download the file =yamwi-yy.mm.tar.gz=, where =yy= stands for the
   year and =mm= for the month of release, and place it somewhere
   accesible from Apache. After that, untar it:
   #+begin_src shell :exports code
   tar -xvf yamwi-yy.mm.tar.gz
   #+end_src
   which creates a new folder called =yamwi=.

2. Execute the =INSTALL= script; it sets up directories and files with
   the neccesary permissions. It also creates temporary folder =tmp=,
   where working files will be placed:
   #+begin_src shell :exports code
   sh yamwi/INSTALL
   #+end_src

3. Installation is now complete, in order to play with the demos just
   type the following address in your browser:
   #+begin_src text :exports code
   http://localhost/path_to_folder/yamwi
   #+end_src
   where =path_to_folder= is not necessary if Yamwi was installed in
   Apache's root system.

Near the beginning of file =yamwi.php=, there is a configuration section:

- =$mode= ::  0, 1, 2, 3 or 4. When 0, Yamwi output is rendered in ASCII Art style;
    when 1, results are rendered in binary files containing TeX output (be sure
    programs texi2dvi, dvips and convert are installed); when 2, output is 
    rendered in enhanced ASCII-Art style, which is easier to read than mode 0;
    when 3, output is returned as a syntactical Maxima expression; when 4, 
    results are based on the nice looking MathJax (http://www.mathjax.org)
    system. Defaults to 2. Response times are shorter in ASCII Art modes.

- =$max_file_time= ::  Yamwi creates some files which are stored in folder
    'tmp'. Every time a user asks for a calculation, Yamwi removes those
    files older, in minutes, than the quantitity indicated by variable 
    '$max_inactive_time', which defaults to 1 minute.

- =$max_process_time= ::  maximum execution time allowed for every Maxima
    process. Default value is 120 sec.

- =$max_num_processes= ::  maximum number of Maxima processes simultaneously
     running on the server. Default value is 30.

* User Packages
Yamwi gives access to all standard Maxima packages. Custom packages can be placed in the =packages=. The file extension should be =.mac= if the package is written in Maxima code, or =.lisp= if it is written in Common Lisp. Yamwi user can =load=
these packages. See the help file =help_en.html=.

* Security
Take care when using this program. To prevent server damages, some
barriers have been designed:

- There is a list of so called *dangerous words*, which prevents the execution of user code when one of these terms is detected in the input. See the global variable =$dangerous_words=.
- The number of running Maxima processes can be limited. See the configuration variable =$max_num_processes=.
- The execution time of Maxima processes can be limited. See the configuration variable =$max_process_time=.

Even with these filters, Yamwi does not guarantee 100% server
security.

* License
This project is distributed under the terms of the GPL (General Public
License). For more information, read file LICENSE.

* Contact

For bug reports, suggestions or collaboration, feel free to contact me at
[[https://github.com/leo-butler/yamwi/issues]].
